### ISSUE TITLE
param to set image

### ISSUE THREAD

**Issue by guai** [yokawasa/kubectl-plugin-socks5-proxy#1]
Hi
In my case this plugin does not work because there is no direct access to docker hub.
Pls add a param to alter the image used from cli

**Comment by yokawasa** [comment]
@guai thanks for the request! I'll work on it
( very sorry for the late response )

**Comment by yokawasa** [comment]
@guai 
it's merged!  So please use v1.0.2 which allows you to alter the image used from cli with `-i` / `--image` param
- https://github.com/kubernetes-sigs/krew-index/pull/1463
- https://github.com/yokawasa/kubectl-plugin-socks5-proxy/releases/tag/v1.0.2
