### ISSUE TITLE
Question : Why I can't find a way without that plugging

### ISSUE THREAD

**Issue by raphaelauv** [yokawasa/kubectl-plugin-socks5-proxy#4]
Sorry my question is from a newbie on kubernetes and network rules.

I have a managed kubernetes cluster ( gke auto-pilot ) where a pod  **A** ( that I can "kubectl exec" ) have access to a managed hidden postgres database.

My wish is to access that database from my host by using the pod **A** as a "bastion/proxy"

With this plugging I simply run `kubectl socks5-proxy` and my host can now resolve and access the host:port of that hidden postgres using the proxy localhost:1080.

I could not found a way without this plugging, is this normal ?

Thank you

**Comment by yokawasa** [comment]
@raphaelauv 

Thank you for the issue (I'm very sorry for the late response)

I believe you can use `kubectl port-forward` to achieve your goal.
Please read this page:

https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod

As one of other solutions, as you know, you also can use this plugin - he plugin actually creates a SOCKS proxy server Pod in a Kubernetes cluster and forwards a local port (default:1080) to the proxy. So you can access to the hidden pod in the k8s cluster via `localhost:1080`

**Comment by yokawasa** [comment]
I'm closing this but please feel free to open an issue if further discussion is needed
